### ISSUE TITLE
咨询个问题

### ISSUE THREAD

**Issue by lhllhx** [gh-tt/cloudflare-scanner#1]
下载缓存是缓存到内存，还是缓存到硬盘，我想挂在路由器上，但是怕对路由器闪存伤害太大

**Comment by gh-tt** [comment]
> 下载缓存是缓存到内存，还是缓存到硬盘，我想挂在路由器上，但是怕对路由器闪存伤害太大

缓存到内存的，运行结束内存占用返还，除了输出结果会存到硬盘
推荐crontab每15分钟运行定时任务设置
*/15 * * * * cd /文件所在路径 && ./cloudflare-scanner >> /文件所在路径/log.txt 2>&1

**Comment by lhllhx** [comment]
路由器运行失败，不太清楚为什么，建议加入详细或调试模式 ，把运行情况大概列一下
![image](https://user-images.githubusercontent.com/52107206/88030990-89628e00-cb6e-11ea-9aa4-2e405066222c.png)

**Comment by gh-tt** [comment]
> 路由器运行失败，不太清楚为什么，建议加入详细或调试模式 ，把运行情况大概列一下
> ![image](https://user-images.githubusercontent.com/52107206/88030990-89628e00-cb6e-11ea-9aa4-2e405066222c.png)

这个是没找到符合延迟限制和ping收包率限制的ip

**Comment by lhllhx** [comment]
> > 路由器运行失败，不太清楚为什么，建议加入详细或调试模式 ，把运行情况大概列一下
> > ![image](https://user-images.githubusercontent.com/52107206/88030990-89628e00-cb6e-11ea-9aa4-2e405066222c.png)
> 
> 这个是没找到符合延迟限制和ping收包率限制的ip

电脑是没有问题的 不清楚为什么路由器有问题

**Comment by gh-tt** [comment]
你可以取ip.txt中几十个ip出来建一个新文件单独测试下看看，路由器性能不够，ping测试，配置文件默认开启了100协程，可能导致测试不准确。我在电脑上测试，2000个ip，每个ping 20次，开启200协程，会出现ping测试耗时好几分钟的情况，这个可能和tcp连接的time  wait状态有关系，端口可能耗尽、抢占。只有几百个ip测试的话，基本几十秒ping测试就完成了

**Comment by lhllhx** [comment]
我把ping协程降低为50 并且删除所有非104开头的ip 路由器顺利3min完成（看来应该是端口耗尽的问题）我打算一天测几次就差不多了，感觉不需要这么频繁换。

![image](https://user-images.githubusercontent.com/52107206/88072510-aff0eb00-cba7-11ea-8295-8378529bbcc7.png)
最后给一个小小的建议，可以加入进度条之类的功能，并在配置中加入开关（看着黑框没进度太痛苦了）
最后感谢作者的贡献

这是我现在路由器的配置 后来人可以参考一下
```
#存放待ping的ip 文件名称（默认为当前文件夹下ip.txt）.
ipFilename: ip.txt
#每个ip段选择的ip数量 如从111.111.111.X这个ip段中随机选择10个ip，该项必须，不能为0且小于等于255
selectCountEveryIp: 3
#ping测试最大协程数(默认100，数字越大越快，但可能影响结果准确性)
pingRoutine: 100
#每个ip ping次数(默认10)
pingCount: 10
#下载测试最大协程数(默认1，数字越大可能影响测试结果)
downloadRoutine: 1
#需下载测试的ip节点个数(默认10)
downloadTestCount: 10
#下载测试时间(默认10,单位为秒)
downloadSecond: 10
#测试资源url，该资源需缓存在cloudflare上
downloadUrl: https://apple.freecdn.workers.dev/105/media/us/iphone-11-pro/2019/3bd902e4-0752-4ac1-95f8-6225c32aec6d/films/product/iphone-11-pro-product-tpl-cc-us-2019_1280x720h.mp4
#筛选ip 最大ping延迟限制（默认200，单位ms）
rttLimit: 200
#筛选ip 最小ping收包率限制（默认0，0<=该值<=100）
recvRateLimit: 90
#是否输出前5个ip数据到txt文件
isOutputTxt: true
```
